### ISSUE TITLE
why no css?

### ISSUE THREAD

**Issue by hanayik** [hanayik/TemporalOrder#7]
@KyleJP22 Why did you delete all the other css in the file "app.css"?

**Comment by KyleJP22** [comment]
When i first opened TemporalOrder on my machine all the file had in it was 
.app-container {
display: flex:
}
which i thought was odd too because i remember you had put more into it.
I had to do a lot of playing around to get everything running smooth that's why i had so many commits. Until i changed the path and installed a few things to make the file update automatically. So maybe when i was doing something with the file it messed it up but i didn't open up the file and remove anything manually.

**Comment by KyleJP22** [comment]
I looked over the commits and found the one where they all got deleted. Still not sure how that happened but i'll fix it.

**Comment by hanayik** [comment]
@KyleJP22 No prob, I just fixed it.
